### ISSUE TITLE
Known issues: Does not work with XPN

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/k8s-multicluster-ingress#56]
List of known issues:
- [x] HTTPS services not supported. Throws an error if https is requested (https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/46)
- [ ] Does not work with XPN (https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/96)
- [x] --force does not work for all resources (https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/79)

**Comment by normanjoyner** [comment]
created an issue (#96) for XPN compatibility. All issues enumerated in this issue have been individually filed and this issue can be removed.

**Comment by nikhiljindal** [comment]
Thanks @normanjoyner 
Updated the list to include link to the new issue.

Will still keep this open as its an easy way to point users to high level known issues and keep track

**Comment by G-Harmon** [comment]
#79 (--force doesn't work) is now fixed. removing that blocker.

**Comment by G-Harmon** [comment]
#46 (HTTPS Ingresses) is closed/fixed now.
